config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 2
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to "/posts/#{@post.id}"
  end

  def edit
  end

  def update
    @post.update_attributes(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def show
  end

  def destroy
    @post.destroy
    redirect_to "/posts"
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :category_id,
      :body
    )
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def find_category_title(category_id)
    category = Category.find(category_id)
    category.title
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          My Blog
        </a>
      </div>

      <!--<form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/posts/new">投稿する</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/posts/edit.html.erb
<div class="col-lg-12">
<%= form_for @post, url: {action: :update} do |f| %>
  <div class="form-group">
    <label for="post_タイトル">タイトル</label>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="post_カテゴリ">カテゴリ</label>
    <%= f.collection_select(:category_id, Category.all, :id, :title, class: "form-control") %>
  </div>
  <div class="form-group">
    <label for="post_テキスト">テキスト</label>
    <%= f.text_area :body, :class => "form-control" %>
  </div>
  <%= f.submit '更新する', :class => "btn btn-primary" %>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="col-md-8">
<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-sm-3">
      <%= f.label :title, "タイトル" %>
      <%= f.search_field :title_or_body_cont, class: "form-control" %>
    </div>
    <%= f.submit "検索", class: "btn btn-default" %>
  </div>
<% end %>

<%= paginate @posts %>
<% @posts.each do |post| %>
  <div class="article">
    <h2><%= post.title %></h2>
    <p><%= post.created_at %></p>
    <p><%= truncate(post.body, :length => 50, :omission => "...") %></p>
    <p><a class="btn btn-default" href="/posts/<%= post.id %>" role="button">続きを読む</a></li>
  </div>
  <hr>
<% end %>
<%= paginate @posts %>
</div>


<div class="col-md-4">
  <div class="thumbnail">
    <% @author = Author.first %>
    <img src="<%= @author.image_url %>" alt="著者イメージ">
    <div class="caption">
      <h3><%= @author.name %></h3>
      <p><%= @author.description %></p>
    </div>
  </div>

  <div class="list-group">
  <% @posts.each_with_index do |post, index| %>
    <% if index >= 5 %>
      <% break %>
    <% end %>
    <%= link_to post.title, post, :class => "list-group-item" %>
  <% end %>
  </div>

</div>

app/views/posts/new.html.erb
<div class="col-lg-12">

<h1>ブログ記事を書く</h1>

<%= form_for @post do |f| -%>
  <div class="form-group">
    <label for="post_タイトル">タイトル</label>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="post_カテゴリ">カテゴリ</label>
    <%= f.text_field :category, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label for="post_テキスト">テキスト</label>
    <%= f.text_area :body, :class => "form-control" %>
  </div>
  <%= f.submit '登録する', :class => "btn btn-primary" %>
<% end %>

</div>

app/views/posts/show.html.erb
<div class="col-lg-12">

<h1><%= @post.title %></h1>
<p>カテゴリ：<%= find_category_title(@post.category_id) %></p>
<p>投稿日：<%= @post.created_at %></p>
<hr>
<p>
  <p><%= simple_format(@post.body) %></p>
</p>
<hr>
<%= link_to "編集する", edit_post_path, :class => "btn btn-default" %>
<%= link_to "削除する", post_path, method: :delete, data: { confirm: "削除しますか？"}, :class => "btn btn-danger" %>

</div>